default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookstore
  database_url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: bookstore_test
  database_url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: bookstore
  database_url: <%= ENV['DATABASE_URL'] %>
